### DISCUSSION TITLE
How implement the page as a path in my domain?

### DISCUSSION THREAD

**Discussion by PabloEmidio** [jpanther/lynx#55] [Q&A]
I have a personal website with its own purpose. I would like to have this project page as a path like `mysite.com/links/` instead of `mysite.com` itself. Is that possible?

Follow this thinking, I thought about create a subdomain where all requests are redirect to the page, but it has a problem with the relative path image. Using:

```toml
# config/_default/server.toml
[[redirects]]
   force = false
   from = '/**'
   status = 200
   to = '/'
```

The image would not load accessing any domain + path. E.g subdomain.mysite.com/links/ the site would try to access `subdomain.mysite.com/links/image/author.jpg` instead of `subdomain.mysite.com/image/author.jpg`
