### ISSUE TITLE
Installation instructions in README.md (Quick start using Hugo) module syntax wrong

### ISSUE THREAD

**Issue by irkode** [jpanther/lynx#155]
### What happened?

The toml snippet is not valid

2. Create `config/_default/module.toml` and add the following:

   ```toml
   [[imports]]
   path = "github.com/jpanther/lynx"
   ```

it should be 

```toml
[module]
  [[module.imports]]
    path = "github.com/jpanther/lynx"
```

### Theme version

latest

### Hugo version

130.0
